### ISSUE TITLE
Support for private-repo examples?

### ISSUE THREAD

**Issue by petemounce** [buildkite-plugins/buildkite-plugin-linter#385]
In my private repo, I have a README.md with this YAML example block in it.

```yaml
steps:
  - command: echo foo
    plugins:
      - ssh://git@github.com/improbable/toolshare-buildkite-plugin.git#v0.0.1: {}
```

It fails linting:

```
$ docker-compose run --rm lint
Creating toolshare-buildkite-plugin_lint_run ... done
TAP version 13
ok 1 - plugin.yml is valid
not ok 2 - No readme config examples found with plugin id 'improbable/toolshare'. Have you configured the linter with the correct plugin id?
ok 3 - Readme version numbers are up-to-date (v0.0.1)
1..3
# failed 1 of 3 tests
# time=85.235ms
```

I _think_ this is because the regexes (https://github.com/buildkite-plugins/buildkite-plugin-linter/blob/master/lib/linters/example-linter.js#L80) are not supporting my I-think-legit example...?
