### ISSUE TITLE
Linter does not allow map syntax in example

### ISSUE THREAD

**Issue by martin-walsh** [buildkite-plugins/buildkite-plugin-linter#457]
Array syntax is mandatory in example

e.g. the following is rejected

```yaml
steps:
  - plugins:
      my-org/my-plugin#v1.0.0:
```

in favour of

```yaml
steps:
  - plugins:
      - my-org/my-plugin#v1.0.0:
```
