### ISSUE TITLE
Allow code examples with invalid version tags

### ISSUE THREAD

**Issue by toothbrush** [buildkite-plugins/buildkite-plugin-linter#485]
Hi! :wave: In the documentation for my Buildkite plugin i'd like to be able to tell users that they can use the `BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH` feature [as described here](https://buildkite.com/docs/plugins/writing#developing-a-plugin-with-a-feature-branch) to get rapid development feedback while making changes to a Buildkite plugin.  I want to provide an example in the docs, something like this:

   ```yaml
   steps:
     - name: ":hiking_boot: Kick off plugin"
       env:
         BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH: "true"
       plugins:
         - ssh://git@github.com/org/bar-buildkite-plugin.git#your-branch-name:
             some_option: foo
   ```

However, the linter is complaining that `your-branch-name` isn't a valid version tag.  I mean, that's correct.  But it's also pretty annoying.  I wonder if folks have a workaround?  I could also attempt to implement, e.g., a whitelist of "always valid" version tags, but that is rather a yak shave for what i want to get done right now.
