### ISSUE TITLE
Allow usage of linter for custom plugins

### ISSUE THREAD

**Issue by joscha** [buildkite-plugins/buildkite-plugin-linter#9]
I wrote https://github.com/joscha/sauce-connect-buildkite-plugin

and the output:
```yml
steps:
  - command: 'yarn && yarn saucelabs-based-tests'
    plugins:
      sauce-connect#v1.0.0: ~
```
makes the linter happy, but technically it needs to be:
```yml
steps:
  - command: 'yarn && yarn saucelabs-based-tests'
    plugins:
      joscha/sauce-connect#v1.0.0: ~
```

as this plugin is not part of the `buildkite-plugins` repo.
